"""
br_neighbours.py
----------------
Conceptual neighbourhood map for the 48 QRPC basic relations.

Two BRs are neighbours if one can transition to the other via an
elementary kinematic movement:
  - Object moves forward or backward along its heading direction
  - Object rotates in place (changes heading, no translation)
  - Both objects rotate synchronously (same direction and speed)
No simultaneous rotation + translation is allowed.

Map: 48 BRs, 144 symmetric pairs, average 6.0 neighbours per BR.
"""

NEIGHBOURS: dict[str, list[str]] = {
    '<X,PLUS,PLUS,PLUS,_,PLUS>': [
        '<X,PLUS,PLUS,PLUS,_,ZERO>',
        '<X,ZERO,PLUS,_,P_TO_M,_>',
        '<PAR_SAME,_,_,PLUS,_,PLUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,PLUS,PLUS,_,ZERO>': [
        '<X,PLUS,PLUS,PLUS,_,PLUS>',
        '<X,PLUS,PLUS,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,PLUS,PLUS,_,MINUS>': [
        '<X,PLUS,PLUS,PLUS,_,ZERO>',
        '<X,PLUS,ZERO,PLUS,_,_>',
        '<PAR_SAME,_,_,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,MINUS,PLUS,_,PLUS>': [
        '<X,PLUS,ZERO,PLUS,_,_>',
        '<X,PLUS,MINUS,PLUS,_,ZERO>',
        '<PAR_OPP,_,_,PLUS,_,PLUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,MINUS,PLUS,_,ZERO>': [
        '<X,PLUS,MINUS,PLUS,_,PLUS>',
        '<X,PLUS,MINUS,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
    ],
    '<X,PLUS,MINUS,PLUS,_,MINUS>': [
        '<X,PLUS,MINUS,PLUS,_,ZERO>',
        '<X,ZERO,MINUS,_,P_TO_M,_>',
        '<PAR_OPP,_,_,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,PLUS,MINUS,MINUS,_,PLUS>': [
        '<X,PLUS,ZERO,MINUS,_,_>',
        '<X,PLUS,MINUS,MINUS,_,ZERO>',
        '<PAR_OPP,_,_,MINUS,_,PLUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,MINUS,MINUS,_,ZERO>': [
        '<X,PLUS,MINUS,MINUS,_,PLUS>',
        '<X,PLUS,MINUS,MINUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
    ],
    '<X,PLUS,MINUS,MINUS,_,MINUS>': [
        '<X,PLUS,MINUS,MINUS,_,ZERO>',
        '<X,ZERO,MINUS,_,M_TO_P,_>',
        '<PAR_OPP,_,_,MINUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,MINUS,PLUS,_,PLUS>': [
        '<X,MINUS,MINUS,PLUS,_,ZERO>',
        '<X,MINUS,ZERO,PLUS,_,_>',
        '<PAR_SAME,_,_,PLUS,_,PLUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,MINUS,PLUS,_,ZERO>': [
        '<X,MINUS,MINUS,PLUS,_,PLUS>',
        '<X,MINUS,MINUS,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,MINUS,PLUS,_,MINUS>': [
        '<X,MINUS,MINUS,PLUS,_,ZERO>',
        '<X,ZERO,MINUS,_,M_TO_P,_>',
        '<PAR_SAME,_,_,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,PLUS,ZERO,PLUS,_,_>': [
        '<X,PLUS,PLUS,PLUS,_,MINUS>',
        '<X,PLUS,MINUS,PLUS,_,PLUS>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,ZERO,MINUS,_,_>': [
        '<X,PLUS,PLUS,MINUS,_,MINUS>',
        '<X,PLUS,MINUS,MINUS,_,PLUS>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,MINUS,ZERO,PLUS,_,_>': [
        '<X,MINUS,MINUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,MINUS>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,ZERO,MINUS,_,_>': [
        '<X,MINUS,MINUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,MINUS>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,PLUS,PLUS,MINUS,_,PLUS>': [
        '<X,PLUS,PLUS,MINUS,_,ZERO>',
        '<X,ZERO,PLUS,_,M_TO_P,_>',
        '<PAR_SAME,_,_,MINUS,_,PLUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,PLUS,MINUS,_,ZERO>': [
        '<X,PLUS,PLUS,MINUS,_,MINUS>',
        '<X,PLUS,PLUS,MINUS,_,PLUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,PLUS,PLUS,MINUS,_,MINUS>': [
        '<X,PLUS,PLUS,MINUS,_,ZERO>',
        '<X,PLUS,ZERO,MINUS,_,_>',
        '<PAR_SAME,_,_,MINUS,_,MINUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,MINUS,PLUS,PLUS,_,PLUS>': [
        '<X,ZERO,PLUS,_,M_TO_P,_>',
        '<X,MINUS,PLUS,PLUS,_,ZERO>',
        '<PAR_OPP,_,_,PLUS,_,PLUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,MINUS,PLUS,PLUS,_,ZERO>': [
        '<X,MINUS,PLUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
    ],
    '<X,MINUS,PLUS,PLUS,_,MINUS>': [
        '<X,MINUS,PLUS,PLUS,_,ZERO>',
        '<X,MINUS,ZERO,PLUS,_,_>',
        '<PAR_OPP,_,_,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,PLUS,MINUS,_,PLUS>': [
        '<X,ZERO,PLUS,_,P_TO_M,_>',
        '<X,MINUS,PLUS,MINUS,_,ZERO>',
        '<PAR_OPP,_,_,MINUS,_,PLUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,MINUS,PLUS,MINUS,_,ZERO>': [
        '<X,MINUS,PLUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
    ],
    '<X,MINUS,PLUS,MINUS,_,MINUS>': [
        '<X,MINUS,PLUS,MINUS,_,ZERO>',
        '<X,MINUS,ZERO,MINUS,_,_>',
        '<PAR_OPP,_,_,MINUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,MINUS,MINUS,_,PLUS>': [
        '<X,MINUS,MINUS,MINUS,_,ZERO>',
        '<X,MINUS,ZERO,MINUS,_,_>',
        '<PAR_SAME,_,_,MINUS,_,PLUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,MINUS,MINUS,_,ZERO>': [
        '<X,MINUS,MINUS,MINUS,_,MINUS>',
        '<X,MINUS,MINUS,MINUS,_,PLUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,MINUS,MINUS,MINUS,_,MINUS>': [
        '<X,MINUS,MINUS,MINUS,_,ZERO>',
        '<X,ZERO,MINUS,_,P_TO_M,_>',
        '<PAR_SAME,_,_,MINUS,_,MINUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,ZERO,PLUS,_,M_TO_P,_>': [
        '<X,PLUS,PLUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,PLUS>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,ZERO,PLUS,_,P_TO_M,_>': [
        '<X,PLUS,PLUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,PLUS>',
        '<OVL_SAME,_,_,_,_,PLUS>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<X,ZERO,MINUS,_,M_TO_P,_>': [
        '<X,MINUS,MINUS,PLUS,_,MINUS>',
        '<X,PLUS,MINUS,MINUS,_,MINUS>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<X,ZERO,MINUS,_,P_TO_M,_>': [
        '<X,MINUS,MINUS,MINUS,_,MINUS>',
        '<X,PLUS,MINUS,PLUS,_,MINUS>',
        '<OVL_SAME,_,_,_,_,MINUS>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<PAR_SAME,_,_,PLUS,_,PLUS>': [
        '<X,PLUS,PLUS,PLUS,_,PLUS>',
        '<X,MINUS,MINUS,PLUS,_,PLUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
    ],
    '<PAR_SAME,_,_,PLUS,_,ZERO>': [
        '<X,PLUS,PLUS,PLUS,_,PLUS>',
        '<X,PLUS,PLUS,PLUS,_,ZERO>',
        '<X,PLUS,PLUS,PLUS,_,MINUS>',
        '<X,MINUS,MINUS,PLUS,_,PLUS>',
        '<X,MINUS,MINUS,PLUS,_,ZERO>',
        '<X,MINUS,MINUS,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,PLUS,_,PLUS>',
        '<PAR_SAME,_,_,PLUS,_,MINUS>',
    ],
    '<PAR_SAME,_,_,PLUS,_,MINUS>': [
        '<X,PLUS,PLUS,PLUS,_,MINUS>',
        '<X,MINUS,MINUS,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,PLUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
    ],
    '<PAR_SAME,_,_,MINUS,_,PLUS>': [
        '<X,PLUS,PLUS,MINUS,_,PLUS>',
        '<X,MINUS,MINUS,MINUS,_,PLUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,PLUS>',
    ],
    '<PAR_SAME,_,_,MINUS,_,ZERO>': [
        '<X,PLUS,PLUS,MINUS,_,PLUS>',
        '<X,PLUS,PLUS,MINUS,_,ZERO>',
        '<X,PLUS,PLUS,MINUS,_,MINUS>',
        '<X,MINUS,MINUS,MINUS,_,PLUS>',
        '<X,MINUS,MINUS,MINUS,_,ZERO>',
        '<X,MINUS,MINUS,MINUS,_,MINUS>',
        '<PAR_SAME,_,_,MINUS,_,MINUS>',
        '<PAR_SAME,_,_,MINUS,_,PLUS>',
    ],
    '<PAR_SAME,_,_,MINUS,_,MINUS>': [
        '<X,PLUS,PLUS,MINUS,_,MINUS>',
        '<X,MINUS,MINUS,MINUS,_,MINUS>',
        '<PAR_SAME,_,_,MINUS,_,ZERO>',
        '<OVL_SAME,_,_,_,_,MINUS>',
    ],
    '<PAR_OPP,_,_,PLUS,_,PLUS>': [
        '<X,PLUS,MINUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,PLUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<PAR_OPP,_,_,PLUS,_,ZERO>': [
        '<X,PLUS,MINUS,PLUS,_,PLUS>',
        '<X,PLUS,MINUS,PLUS,_,ZERO>',
        '<X,PLUS,MINUS,PLUS,_,MINUS>',
        '<X,MINUS,PLUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,ZERO>',
        '<X,MINUS,PLUS,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,PLUS,_,PLUS>',
        '<PAR_OPP,_,_,PLUS,_,MINUS>',
    ],
    '<PAR_OPP,_,_,PLUS,_,MINUS>': [
        '<X,PLUS,MINUS,PLUS,_,MINUS>',
        '<X,MINUS,PLUS,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,PLUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<PAR_OPP,_,_,MINUS,_,PLUS>': [
        '<X,PLUS,MINUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,PLUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,PLUS>',
    ],
    '<PAR_OPP,_,_,MINUS,_,ZERO>': [
        '<X,PLUS,MINUS,MINUS,_,PLUS>',
        '<X,PLUS,MINUS,MINUS,_,ZERO>',
        '<X,PLUS,MINUS,MINUS,_,MINUS>',
        '<X,MINUS,PLUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,ZERO>',
        '<X,MINUS,PLUS,MINUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,PLUS>',
        '<PAR_OPP,_,_,MINUS,_,MINUS>',
    ],
    '<PAR_OPP,_,_,MINUS,_,MINUS>': [
        '<X,PLUS,MINUS,MINUS,_,MINUS>',
        '<X,MINUS,PLUS,MINUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,ZERO>',
        '<OVL_OPP,_,_,_,_,MINUS>',
    ],
    '<OVL_SAME,_,_,_,_,PLUS>': [
        '<X,PLUS,PLUS,PLUS,_,PLUS>',
        '<X,PLUS,PLUS,MINUS,_,PLUS>',
        '<X,MINUS,MINUS,PLUS,_,PLUS>',
        '<X,MINUS,MINUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,ZERO>',
        '<X,MINUS,PLUS,PLUS,_,MINUS>',
        '<X,MINUS,PLUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,ZERO>',
        '<X,MINUS,PLUS,MINUS,_,MINUS>',
        '<X,ZERO,PLUS,_,M_TO_P,_>',
        '<X,ZERO,PLUS,_,P_TO_M,_>',
        '<X,MINUS,ZERO,PLUS,_,_>',
        '<X,MINUS,ZERO,MINUS,_,_>',
        '<PAR_SAME,_,_,PLUS,_,PLUS>',
        '<PAR_SAME,_,_,MINUS,_,PLUS>',
    ],
    '<OVL_SAME,_,_,_,_,MINUS>': [
        '<X,PLUS,PLUS,PLUS,_,MINUS>',
        '<X,PLUS,PLUS,MINUS,_,MINUS>',
        '<X,MINUS,MINUS,PLUS,_,MINUS>',
        '<X,MINUS,MINUS,MINUS,_,MINUS>',
        '<X,PLUS,MINUS,PLUS,_,PLUS>',
        '<X,PLUS,MINUS,PLUS,_,ZERO>',
        '<X,PLUS,MINUS,PLUS,_,MINUS>',
        '<X,PLUS,MINUS,MINUS,_,PLUS>',
        '<X,PLUS,MINUS,MINUS,_,ZERO>',
        '<X,PLUS,MINUS,MINUS,_,MINUS>',
        '<X,ZERO,MINUS,_,M_TO_P,_>',
        '<X,ZERO,MINUS,_,P_TO_M,_>',
        '<X,PLUS,ZERO,MINUS,_,_>',
        '<X,PLUS,ZERO,PLUS,_,_>',
        '<PAR_SAME,_,_,PLUS,_,MINUS>',
        '<PAR_SAME,_,_,MINUS,_,MINUS>',
    ],
    '<OVL_OPP,_,_,_,_,PLUS>': [
        '<X,PLUS,PLUS,PLUS,_,PLUS>',
        '<X,PLUS,PLUS,PLUS,_,ZERO>',
        '<X,PLUS,PLUS,PLUS,_,MINUS>',
        '<X,PLUS,PLUS,MINUS,_,PLUS>',
        '<X,PLUS,PLUS,MINUS,_,ZERO>',
        '<X,PLUS,PLUS,MINUS,_,MINUS>',
        '<X,PLUS,MINUS,PLUS,_,PLUS>',
        '<X,PLUS,MINUS,MINUS,_,PLUS>',
        '<X,MINUS,PLUS,PLUS,_,PLUS>',
        '<X,MINUS,PLUS,MINUS,_,PLUS>',
        '<X,ZERO,PLUS,_,M_TO_P,_>',
        '<X,ZERO,PLUS,_,P_TO_M,_>',
        '<X,PLUS,ZERO,PLUS,_,_>',
        '<X,PLUS,ZERO,MINUS,_,_>',
        '<PAR_OPP,_,_,PLUS,_,PLUS>',
        '<PAR_OPP,_,_,MINUS,_,PLUS>',
    ],
    '<OVL_OPP,_,_,_,_,MINUS>': [
        '<X,MINUS,MINUS,PLUS,_,PLUS>',
        '<X,MINUS,MINUS,PLUS,_,ZERO>',
        '<X,MINUS,MINUS,PLUS,_,MINUS>',
        '<X,MINUS,MINUS,MINUS,_,PLUS>',
        '<X,MINUS,MINUS,MINUS,_,ZERO>',
        '<X,MINUS,MINUS,MINUS,_,MINUS>',
        '<X,PLUS,MINUS,PLUS,_,MINUS>',
        '<X,PLUS,MINUS,MINUS,_,MINUS>',
        '<X,MINUS,PLUS,PLUS,_,MINUS>',
        '<X,MINUS,PLUS,MINUS,_,MINUS>',
        '<X,ZERO,MINUS,_,M_TO_P,_>',
        '<X,ZERO,MINUS,_,P_TO_M,_>',
        '<X,MINUS,ZERO,PLUS,_,_>',
        '<X,MINUS,ZERO,MINUS,_,_>',
        '<PAR_OPP,_,_,PLUS,_,MINUS>',
        '<PAR_OPP,_,_,MINUS,_,MINUS>',
    ],
}
